
# config file
configfile: "config/config.yml"

# load rules
include: "rules/create_baseline_predictors.smk"
include: "rules/copy_baseline_predictors_to_oak.smk"

# add ABC sample files to config object
include: "scripts/add_samples_to_config.py"

# compute all baseline predictors
rule all:
  input:
    expand("{outdir}/{sample}/{peaks}/{pred}.tsv.gz", peaks = ["dhs"], sample = config["samples"],
           outdir = config["outdir"], pred = ["dist_to_tss", "nearest_expressed_gene"]),
    expand("{outdir}/{sample}/{peaks}/{pred}.tsv.gz", peaks = ["dhs", "abc"],
           sample = config["dnase_pred_samples"] + config["h3ka7ac_pred_samples"],
           outdir = config["outdir"],
           pred = ["dist_to_tss", "dist_to_gene", "within_100kb_of_tss", "within_100kb_of_gene",
                   "within_100kb_of_expressed_tss", "within_100kb_of_expressed_gene", "nearest_tss",
                   "nearest_gene", "nearest_expressed_tss", "nearest_expressed_gene"]),
    expand("{outdir}/{sample}/{peaks}/DHS_reads_by_dist_to_{annot}{ext}",
           sample = config["dnase_pred_samples"], outdir = config["outdir"], peaks = ["dhs", "abc"],
           annot = ["tss", "gene"], ext = [".tsv.gz", "_norm.tsv.gz"]),
    expand("{outdir}/{sample}/{peaks}/H3K27ac_reads_by_dist_to_{annot}{ext}",
           sample = config["h3ka7ac_pred_samples"], outdir = config["outdir"], peaks = ["dhs", "abc"],
           annot = ["tss", "gene"], ext = [".tsv.gz", "_norm.tsv.gz"])       
