
# output directory for output (default: ./results)
outdir: "/scratch/users/agschwin/baseline_predictors"

# lookup table containing read files for ABC biosamples
sample_files: "config/e2g_baseline_preds_input_files_bam.tsv"

# gene and TSS annotation files
annot:
  tss: "resources/genome_annotations/CollapsedGeneBounds.hg38.TSS500bp.bed"
  gene: "resources/genome_annotations/CollapsedGeneBounds.hg38.bed"
  chrs: "resources/genome_annotations/GRCh38_EBV.chrom.sizes.tsv"
  regular_chrs: "resources/genome_annotations/GRCh38_regular_chroms.bed"
  
# samples for which more extensive lists of baseline predictors will be computed
dnase_pred_samples:
- dorsolateral_prefrontal_cortex_ENCSR001QTZ
- brain_ENCSR026EOM
- prostate_gland_ENCSR564FZH
- epithelial_cell_of_prostate_ENCSR000EPU
- skeletal_muscle_cell_ENCSR000EQA
- skeletal_muscle_myoblast_ENCSR000EOO
- suprapubic_skin_ENCSR101QXF
- suprapubic_skin_ENCSR709IYR
- pancreas_ENCSR056PFI
- pancreas_ENCSR178JBL
- lung_ENCSR006IJP
- lung_ENCSR076YBB
- lower_leg_skin_ENCSR361DND
- lower_leg_skin_ENCSR579KDC
- GM12878_ENCSR000EMT
- liver_ENCSR158YXM
- liver_ENCSR562FNN
- heart_left_ventricle_ENCSR070CMW
- heart_left_ventricle_ENCSR222CLC
- sigmoid_colon_ENCSR276ITP
- sigmoid_colon_ENCSR391YAV
- transverse_colon_ENCSR340MRJ
- transverse_colon_ENCSR760QZM
- K562_ENCSR000EOT

h3ka7ac_pred_samples:
- dorsolateral_prefrontal_cortex_ENCSR001QTZ
- prostate_gland_ENCSR564FZH
- epithelial_cell_of_prostate_ENCSR000EPU
- skeletal_muscle_myoblast_ENCSR000EOO
- suprapubic_skin_ENCSR101QXF
- suprapubic_skin_ENCSR709IYR
- pancreas_ENCSR056PFI
- pancreas_ENCSR178JBL
- lung_ENCSR006IJP
- lung_ENCSR076YBB
- GM12878_ENCSR000EMT
- liver_ENCSR158YXM
- liver_ENCSR562FNN
- heart_left_ventricle_ENCSR070CMW
- heart_left_ventricle_ENCSR222CLC
- sigmoid_colon_ENCSR276ITP
- sigmoid_colon_ENCSR391YAV
- transverse_colon_ENCSR340MRJ
- transverse_colon_ENCSR760QZM
- K562_ENCSR000EOT

